server:
  port: 8025
spring:
  datasource:
    url: jdbc:mysql://192.168.137.132:3306/duan_cart?useSSL=false&characterEncoding=utf8
    username: root
    password: dxb343
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: commonservice
#  elasticsearch:
#    rest:
#      uris: http://192.168.137.132:9200
#  elasticsearch:
#    rest:
#      uris: 192.168.137.132:9200
mybatis:
  type-aliases-package: com.springcloud.common.Entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


minio:
  endPoint: http://192.168.137.132:9000/
  accessKey: dxb343
  secretKey: duanxiaobo343
  bucketName: duan
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50