server:
  port: 8085
spring:

  datasource:
    url: jdbc:mysql://192.168.137.132:3306/duan_cart?useSSL=false&characterEncoding=utf8
    username: root
    password: dxb343
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: cartservice
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
---
server:
  port: 8085
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://mysql:3306/hayishu_cart?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  application:
    name: cartservice
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
---
spring:
  profiles:
    active: dev
