server:
  port: 8026
spring:

  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://192.168.137.132:3306/duan_store?useSSL=false&characterEncoding=utf8
    username: root
    password: dxb343
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50